env:
  global:
    - CC_TEST_REPORTER_ID=68a6ae89e5dc21454232d9845872f5f50ea5e5298d593eb9bcb9ad85cffd781a
language: ruby
rvm:
  - 2.7
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
before_install: gem install bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rubocop
  - bundle exec rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
